apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: ticketing
build:
  local:
    push: false
  artifacts:
    - image: shreeanshgupta/auth
      context: ./backend/auth
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: shreeanshgupta/client
      context: ./client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: "**/*.js"
            dest: .
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/auth-depl.yaml
      - ./infra/k8s/mongo-sset.yaml
      - ./infra/k8s/mongo-pvc.yaml
      - ./infra/k8s/ingress-service.yaml
      - ./infra/k8s/client-depl.yaml
